### ISSUE TITLE
Artifact not available in Maven Central

### ISSUE THREAD

**Issue by rowanseymour** [tradier/dropwizard-raven#1]
According to README, project is in Maven Central but doesn't appear to be so http://search.maven.org/#search%7Cga%7C1%7Cdropwizard-raven

**Comment by stve** [comment]
Hi, thanks for checking this out. I've had difficulties figuring out how to publish to maven central. While I've been testing this and we're close to making use of this, we haven't started using it in our systems just yet. I believe you can pickup a snapshot, can you try grabbing `0.1.1-SNAPSHOT`? I'll take another crack at getting this published properly as well. Thanks.

**Comment by rowanseymour** [comment]
Thanks. I didn't want to put a snapshot version on our servers but was able to locally build 0.0.1 by checking out commit fc2d93f7710d4e32ca727110d3eb3093b15b4de6

This isn't related but you have gotten this working alongside other appenders? I'm running into problems where the maven shade plugin isn't merging `io.dropwizard.logging.AppenderFactory` so it breaks as soon as I have different appenders. Not sure where that problem lies yet.

**Comment by rowanseymour** [comment]
Nevermind - upgraded shade plugin from 1.6 to 2.3 and all is well

**Comment by eoinoconnell** [comment]
Hey, Any progress on getting this on Maven Central?

**Comment by rowanseymour** [comment]
Happy to help in any way get this into the repo...

**Comment by stve** [comment]
hi @rowanseymour, your help would be most welcome. I'm a bit of a noob when it comes to maven and publishing, etc. I've been able to perform SNAPSHOT releases without problems but can't seem to figure out the right workflow for doing the same to the staging repository. 

I've tried following [the guide](http://central.sonatype.org/pages/apache-maven.html) but somehow it didn't work for me. Suggestions welcome. Thanks!

**Comment by rowanseymour** [comment]
Hmm they don't make it simple! You tried adding configurations for the maven-gpg-plugin and nexus-staging-maven-plugin plugins?

I'd recommend using the [release plugin](http://maven.apache.org/maven-release/maven-release-plugin) too for handling the version changes.

**Comment by rowanseymour** [comment]
Frustrating to see this still hasn't made it into Maven Central. Perhaps time for those of us that want this to fork?

**Comment by fpn** [comment]
+1

**Comment by stve** [comment]
version `0.1.2` has now been released to Maven Central. I'll be releasing versions compatible with recent versions of dropwizard shortly.

**Comment by fpn** [comment]
Thank you!!

**Comment by rowanseymour** [comment]
Likewise, thanks! 0.1.2 is working fine for us

**Comment by stve** [comment]
@rowanseymour @fpn out of curiosity, what version(s) of Dropwizard are you running?

**Comment by rowanseymour** [comment]
0.8.0 for https://github.com/rapidpro/mage
