### ISSUE TITLE
Upgrade to use dropwizard 1.0.0

### ISSUE THREAD

**Issue by Soniaroxana** [tradier/dropwizard-raven#12]

**Comment by stve** [comment]
Hi @Soniaroxana I plan to release support for this very soon. You may want to follow #11 to see when it lands. Thanks!

**Comment by Soniaroxana** [comment]
@stve Any news on when that pull request might get merged?

**Comment by Soniaroxana** [comment]
@stve is anyone working on that PR? If not, could I help working on it to get it merged?

**Comment by stve** [comment]
I've been making steady progress on a 1.0.0 release, should be out very soon. Since I'm targeting 1.0.0 for this release version, I want to be sure I have the public interface locked down properly.

https://github.com/tradier/dropwizard-raven/compare/1.0.0

**Comment by Soniaroxana** [comment]
Thanks for your prompt reply, I'll be watching that then

**Comment by stve** [comment]
I've just released version `1.0.0-1` and it should be available in the central repository shortly. Sorry for the delay.
