### ISSUE TITLE
Publish 0.9.X release with DroppingRavenLoggingFilter fix

### ISSUE THREAD

**Issue by loganlinn** [tradier/dropwizard-raven#16]
Any chance we could release a 0.9.X (0.9.3 would be next) release that includes this fix? https://github.com/tradier/dropwizard-raven/commit/eb2285ddcdb5d78e5fce3be5e539a875ea3d809c

It is a pretty nasty bug to APPROVE everything because it makes it impossible to wrap the appender with additional functionality (filters) without hacks.

Upgrading to Dropwizard 1.0+ is not an option for me at the moment, unfortunately.

**Comment by stve** [comment]
Hi @loganlinn I can look at getting a release out. You may not be using maven, but if you are, have you tried excluding the Dropwizard dependency?

```
<dependency>
    <groupId>com.tradier</groupId>
    <artifactId>dropwizard-raven</artifactId>
    <version>1.0.0-1</version>
    <exclusions>
        <exclusion>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-core</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by loganlinn** [comment]
Looking into a release would be much appreciated!

I have indeed tried and it unfortunately isn't an option. Dropwizard made
API changes to AppenderFactory in their 1.X that this library implements.
When this library upgraded to DW 1.X, it is in turn no longer compatible
with projects running DW 0.9.X or older.

**Comment by stve** [comment]
@loganlinn gotcha, I couldn't remember what changes took place when.

**Comment by stve** [comment]
I just backported the change to the 0.9.x release branch and shipped version 0.9.3. It should land in the central repository shortly. 😄

**Comment by stve** [comment]
@loganlinn did 0.9.3 fix things for you?

**Comment by stve** [comment]
presumably this is fixed, @loganlinn feel free to re-open if not.
