### ISSUE TITLE
Feature request - Migrate to io.sentry packages

### ISSUE THREAD

**Issue by StephenSouness** [tradier/dropwizard-raven#17]
Sentry have overhauled their Java API and renamed its associated packages and artefacts.

Is there an intention to produce an updated version of dropwizard-raven to align with the latest available implementation?

**Comment by stve** [comment]
I've followed the development of `sentry-java` and seen the newer 1.x releases. Unfortunately, I haven't been able to figure out the best way to continue to expose the same API currently supported by `dropwizard-raven` with the latest versions. 

Upgrading `sentry-java` may mean changing the public API and removing some of the currently available [configuration settings](https://github.com/tradier/dropwizard-raven#configuration-settings) that cannot be supported going forward.

I'd like to upgrade to keep this current but need to give this more thought.

**Comment by StephenSouness** [comment]
Yeah, it's a tricky one.

I could see future new users coming along and being confused as to why a library for Sentry would have Raven in the name.  So perhaps it might be best to create a new project and abandon some backwards compatibility.

Do you have a list of the settings that might drop off with this approach?

**Comment by stve** [comment]
> So perhaps it might be best to create a new project and abandon some backwards compatibility.

This is probably the best approach

> Do you have a list of the settings that might drop off with this approach?

I had a branch where I started an attempt to upgrade to `sentry-java`, hopefully I still have it around...

**Comment by stve** [comment]
So, upon further investigation, I was mistaken. They've removed programmatic access to configuration in the `SentryAppender` and instead recommend [configuration via a properties file](https://docs.sentry.io/clients/java/config/). 

This actually simplifies things quite a bit. I still think `dropwizard-sentry` is probably the right approach vs. adapting this library to these new conventions.

**Comment by StephenSouness** [comment]
I suppose that means we can close this issue, as it will not be related to this project / repository.
