### ISSUE TITLE
Publish latest version on Maven Central?

### ISSUE THREAD

**Issue by csstaub** [tradier/dropwizard-raven#8]
Hi, it appears that the latest version on Maven Central is 0.7.1.

Would it be possible to publish 0.8.0, 0.9.0 on Maven Central as well?

**Comment by stve** [comment]
hi @csstaub thanks for pointing this out. I'm not sure what happened to 0.9.0 but I fully expected it to be available on Maven Central. I'll take a look...

**Comment by stve** [comment]
I just released the latest version as 0.9.1, I had planned on releasing a 0.8.x version to target Dropwizard 0.8 but their release schedule has exceeded ours and we just ended up upgrading all of our Dropwizard apps to 0.9.x.

**Comment by csstaub** [comment]
Cool. thanks @stve!
